const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {test}=require('node:test');
const source=fs.readFileSync(__dirname+'/../common/app/web/scripts/detail_state.js','utf8');
function setup(){
 let finish;const state={rootPath:'/library',apiReady:true,selectedPostPath:'collection/c/card',selectedDetailItemId:'old',posts:[],collections:[]};
 const calls=[],renders=[];
 const ctx=vm.createContext({library_state:state,screen_state:{current_screen:'b_detail'},qApi:(url,payload)=>{calls.push({url,payload});return new Promise(r=>finish=r)},normalizeServerPost:p=>p,mergeIndexedPostsIntoWorkingSet:posts=>{state.posts=posts},renderDetailViews:o=>renders.push(o)});
 vm.runInContext(source.slice(0,source.indexOf('function selectLibraryPost(')),ctx);
 return {ctx,state,calls,renders,finish:p=>finish({post:p}),run:()=>ctx.refreshBuildDetailFromDisk()};
}
test('fresh disk items render without changing selection; concurrent requests share one read',async()=>{const s=setup();const a=s.run(),b=s.run();assert.equal(s.calls.length,1);assert.equal(s.calls[0].payload.refresh_from_disk,true);s.finish({folder_path:s.state.selectedPostPath,items:[{file:'old.png'},{file:'new.mp4'}]});await Promise.all([a,b]);assert.equal(s.state.posts[0].items.length,2);assert.equal(s.state.selectedDetailItemId,'old');assert.equal(s.renders.length,1)});
test('response after navigation does not replace current card',async()=>{const s=setup();const a=s.run();s.state.selectedPostPath='collection/c/other';s.finish({items:[]});await a;assert.equal(s.renders.length,0);assert.equal(s.state.posts.length,0)});
test('Imagine and remote paths do not trigger local scan',async()=>{const s=setup();s.ctx.screen_state.current_screen='i_detail';await s.run();assert.equal(s.calls.length,0);s.ctx.screen_state.current_screen='b_detail';s.state.selectedPostPath='__pending/job';await s.run();assert.equal(s.calls.length,0)});
test('local title refresh bypasses Imagine synchronization',async()=>{let handler;const calls=[];const ctx=vm.createContext({document:{getElementById:()=>({addEventListener:(e,f)=>handler=f})},screen_state:{current_screen:'b_detail'},library_state:{},showMainRefreshLoading(){},waitForRefreshPaint:async()=>{},refreshImagineSavedMain:async()=>{calls.push('imagine')},refreshCurrentMainView:async()=>{calls.push('local')},hideMainRefreshLoading(){},setLibraryMessage(){},imagineViewValue:()=> 'imagine'});const text=fs.readFileSync(__dirname+'/../common/app/web/scripts/sidebar_events.js','utf8');vm.runInContext(text.slice(text.indexOf('let titleRefreshInProgress'),text.indexOf('let brandImagineReloading')),ctx);for(const screen of ['b_main','collection_main','2nd_main','b_detail']){ctx.screen_state.current_screen=screen;await handler()}assert.deepEqual(calls,['local','local','local','local']);ctx.screen_state.current_screen='i_main';ctx.library_state.iMainView='imagine';await handler();assert.equal(calls.at(-1),'imagine')});
